### ISSUE TITLE
psql: FATAL:  role "superuser" does not exist

### ISSUE THREAD

**Issue by freemember007** [subzerocloud/postgrest-starter-kit#14]
when I modify my code on data/src/api/data/*.sql and save, the zubZero devtools reports this error.
what about it ?

─Logs───────────────────────────────────────────────────────────┐
│./db/src/data/todo.sql changed                                  │
│Starting code reload ------------------------                   │
│psql: FATAL:  role "superuser" does not exist                   │
│                                                                │
│Ready ---------------------------------------                   │
│psql: FATAL:  role "superuser" does not exist

**Comment by ruslantalpa** [comment]
Before bringing the stack up, make sure you are not running postgresql on your host (port 5432)

**Comment by freemember007** [comment]
yes , I have another postgres running in 5432, so i modify docker postgresql's port to  5431:5432.

**Comment by ruslantalpa** [comment]
Devtools for now do not support another port, should be an easy fix but for now, that's the reason for the error

**Comment by ruslantalpa** [comment]
this issue is tracked here https://github.com/subzerocloud/subzero-cli/issues/12
