### ISSUE TITLE
Line endings of .sh files break process on Windows 10

### ISSUE THREAD

**Issue by synapseradio** [subzerocloud/postgrest-starter-kit#23]
Hi - 

First off, thank you so much for creating this starter kit. It's a huge help.

I wanted to submit this issue to let you know that there is a ( solvable ) problem that prevents running this on Windows 10, and probably other versions of Windows as well.

Windows has different line endings as opposed to Unix / OSX - CRLF instead of LF - which makes the .sh files in the project kick out errors in the PostgREST and RabbitMQ boxes due to unrecognized newline characters.

The way that I fixed it was to download [dos2unix](https://sourceforge.net/projects/dos2unix/files/) , and run 

> dos2unix openresty/entrypoint.sh
> dos2unix db/src/init.sh
> docker-compose up -d

in a terminal opened in the root directory. Once that happened, everything ran smoothly. I did not run it on the test scripts but I imagine the same thing would need to happen with those.

It was an easy fix, but a non-obvious solution for me. I don't know if there's a way to detect and fix this automatically, but if there is, I'm sure there are fellow travelers out there who would appreciate it. In any case, I'm happy to submit a PR to add the solution above to the documentation. Thanks again!

**Comment by ruslantalpa** [comment]
I think this isa case of git auto converting line endings in files when clong.

The issue is explained here. https://techblog.dorogin.com/case-of-windows-line-ending-in-bash-script-7236f056abe

Please try configuring git then clone again.
If this does not solve this, please reopen.
