### ISSUE TITLE
problem at the end of API core tutorial with sub join

### ISSUE THREAD

**Issue by rkoberg** [subzerocloud/postgrest-starter-kit#30]
Hi Rusian! I have been trying this out for a couple of weeks. Extremely helpful. Read the docs and went through your tutorial. There was one small problem at the very end of the API core part of the tutorial. The comments(body) sub join does not work:
```
--data-urlencode select="id,name,projects(id,name,comments(body),tasks(id,name,comments(body)))" | \
```
But this does work:
```
--data-urlencode select="id,name,projects(id,name,comments(body),tasks(id,name))" | \
```
Perhaps this is a bug in postgrest or just a change?

**Comment by ruslantalpa** [comment]
hey, sorry this slipped my inbox.
Not sure what's going on, i think i checked that url and it used to work, maybe try a restart of postgrest?

What is the error you are getting?
also might be related to this recent enhancement (not released yet) https://github.com/begriffs/postgrest/issues/1078

Once we finish outstanding tasks, i'll go over the tutorial again (the most recent docs are here https://docs.subzero.cloud)

**Comment by ruslantalpa** [comment]
Let's track this here 
https://github.com/subzerocloud/postgrest-starter-kit/issues/45
