### ISSUE TITLE
Revoke execute on functions from public

### ISSUE THREAD

**Issue by grotsev** [subzerocloud/postgrest-starter-kit#35]
https://github.com/subzerocloud/postgrest-starter-kit/blob/55d6b6a1e0467d05da2378db9ca9c4f5d6398dba/db/src/libs/auth/api/login.sql#L34-L35

It is possible to forget to revoke grant on some function. To prevent this possibility at once we can revoke on every function at the very beginning.

```sql
alter default privileges revoke execute on functions from public;
```

**Comment by ruslantalpa** [comment]
@grotsev while a good suggestion, it might have some problems (I have not researched this in detail).
see these links
https://github.com/PostgREST/postgrest-docs/issues/104#issuecomment-422474253
http://postgrest.org/en/v5.1/api.html#function-privileges


if it's safe to do it with this one line, i'll gladly accept a PR cleaning up all the `revoke` statements
