### ISSUE TITLE
openresty module not found

### ISSUE THREAD

**Issue by ilkosta** [subzerocloud/postgrest-starter-kit#36]
Hi,

trying to run the docker-compose, the instance of `openresty/openresty:jessie` return some the errors:

module `ngx_http_lua_cache_module.so` not found, than 
`lualib/user_code/hooks.lua:6: module 'subzero.jwt_session_cookie' not found`

some hints?

**Comment by ruslantalpa** [comment]
just copying code from the other starter kit into this one does not work :)

**Comment by ruslantalpa** [comment]
subzero starter kit is a "superset" of postgrest starter kit and it uses custom openresty/postgrest images to work

**Comment by ilkosta** [comment]
Thanks :)
