### ISSUE TITLE
Getting Cannot find module 'C:\Projects\postGrest\subzero-base-project'

### ISSUE THREAD

**Issue by ElixirMike** [subzerocloud/postgrest-starter-kit#56]
I installed the npm, docker and then the subzero cli (all seemed to install fine).
I then run the command subzero base-project and am getting this error:

C:\Projects\postGrest>subzero base-project
internal/modules/cjs/loader.js:783
    throw err;
    ^

Error: Cannot find module 'C:\Projects\postGrest\subzero-base-project'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:685:27)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

Any ideas what I'm missing? I'm running this on Windows 10 Pro

**Comment by ruslantalpa** [comment]
try `subzero-base-project`

**Comment by ruslantalpa** [comment]
this is a problem in a upstream package.
for some reason I thought it was fixed but it seems not, i'll bring the notice back
basically it means on win instead of `subzero command` you do `subzero-command`

**Comment by ElixirMike** [comment]
That was it...worked with subzero-base-project. Thx!

**Comment by ElixirMike** [comment]
Another quick question...the stack is up and running, but when I run the test call
curl http://localhost:8080/rest/todos?select=id,todo

I get a "permission denied". I'm assuming that's because the anonymous role wasn't granted privileges to the todos view? 

In terms of setup, is there an additional script I should run in the db to grant privs?

**Comment by ruslantalpa** [comment]
No select means `select *` which means you are requesting the `owner` column and for that particilar column anonymous user does not have rights
