### ISSUE TITLE
Question about fundamental differences between postgrest-starter-kit vs subzero-starter-kit

### ISSUE THREAD

**Issue by pongraczi** [subzerocloud/postgrest-starter-kit#60]
Hi,

I just started to learn postgrest-starter-kit, subzero-starter-kit and jekirl/postgrest-starter-kit and I found that, even they more-or-less provide solution for the "same" problem, they provide different functionality and services when we look at the details.  

If I am right, some basic differences are:  
* subzero-starter-kit focuses on using postgrest-plus in the background and provide tools for easy subzerocloud migration/support
* postgrest-starter-kit is for open-source postgrest not as tightly boundled to subzero
* jekirl/postgrest-starter-kit is a restructured and modified subzero-starter-kit
* all-of-them basically based on docker
* only subzero provides a logout function which deletes the cookie on the client using set-header function

| Feature | subzero-* | postgrest-* | jekirl-* |
|------------|---------------|---------------|------------|
| postgrest         | | X | X |
| postgrest-plus (1 connection)         | X | | |
| docker image all-included except pgsql | X | | |
| separate docker images for components (db, postgrest, rabbitmq, openresty) | | X | X |
| supports cookies via set-header | X | | |
| provides logout function out of box by deleting cookie | X | | |

Anything else, which should be important?  
(I will extend this post as I will have more time)

**Comment by ruslantalpa** [comment]
The first major difference is that subzero-* (while the code in repo is MIT) uses the docker images from subzero which are commercial products.
Other notes:
* jekirl-* seems to be a fork of the old postgrest starter kit, not seeing any "restructuring/improvements"
* cookies-* can be used postgrest-* but the thing that makes them work in this context is the "cookie auto refresh" mechanism which is part of the subzero's commercial offering.
* separate containers - there are separate containers for subzero-* also however a single container is a feature, not a weakness (easier to deploy, faster intercontainer communication ) 
* subzero-* (through a combination of code in postgrest-plus and openresty) provides analytical queries (groupby, window functions), function call in select, graphql api and (upcomming) odata api.

that's a bird-eye view

**Comment by pongraczi** [comment]
Thank you, that explain what I experienced when I evaluated all the three variants.  
From my point of view, docker is not an option, but it was really easy to test them and I can imagine the benefits of using them for those folks, who use docker as basis.  

Thanks again!

**Comment by ruslantalpa** [comment]
docker is not the only option (after all it only wraps binaries configs and lua scripts) however it's much more tedious to setup

**Comment by pongraczi** [comment]
Sorry, my bad, I was not so careful when I wrote that.   
So, I have different existing infrastructures where I plan to use postgrest-starter-kit, but without any docker related magic or subzero-cli. This is because I prefer the existing infrastructure, where I already have some of the stack components.  

I really like this kind of stack (pgsql + postgrest + rabbitmq + openresty) and the way you bundled into a template in your commercial container with postgrest-plus and into an open source free psk.
